WebApplication10/WebApplication10/WebApplication10/Models/Instructor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication10.Models
{
    public class Instructor
    {
        public int ID { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        

        public virtual IEnumerable<Course> Courses { get; set; }

        public override bool Equals(object obj)
        {
            var item = obj as Instructor;

            if (item == null)
            {
                return false;
            }

            if (FirstName.Equals(item.FirstName)&&LastName.Equals(item.LastName))
            {
                return true;
            }

            return false;
        }
    }

}

WebApplication10/WebApplication10/WebApplication10/Controllers/InstructorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication10.Context;
using WebApplication10.Models;

namespace WebApplication10.Controllers
{
    public class InstructorsController : Controller
    {
        private SchoolRepository repository = new SchoolRepository(new SchoolContext());



        public ActionResult Index()
        {
            repository.getInstructors();
            var instructors = repository.getInstructors();
            return View(instructors);
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            Instructor instructor = repository.getInstructor(id);
            if (instructor == null)
            {
                return HttpNotFound();
            }
            return View(instructor);
        }

        public ActionResult Filter()
        {
            ViewBag.Instructors = new SelectList(repository.getInstructors(),"ID", "LastName");
            ViewBag.StartDate = new DateTime();
            ViewBag.EndDate = new DateTime();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Filter(Instructor instructor, DateTime StartDate, DateTime EndDate)
        {


            var coursesForInstructor = repository.getCoursesForInstructors(instructor.ID);

            var studentsThatPassed = repository.getStudentsThatPassed(coursesForInstructor, StartDate, EndDate);


            return View("ListOfStudents",studentsThatPassed);
        }
        public ActionResult ListOfStudents(IEnumerable<Enrollment> enrollments)
        {
            return View(enrollments);
        }
        protected override void Dispose(bool disposing)
        {
            repository.dispose(disposing);
            base.Dispose(disposing);
        }
    }
}

WebApplication10/WebApplication10/WebApplication10/Views/Instructors/Details.cshtml
@model WebApplication10.Models.Instructor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Instructor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Courses)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Courses)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication10/WebApplication10/WebApplication10/Views/Instructors/Filter.cshtml
@model WebApplication10.Models.Instructor

@{
    ViewBag.Title = "Filter";
}

<h2>View</h2>


@using (Html.BeginForm("Filter","Instructors",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Instructor</h4>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.ID, (SelectList)ViewBag.Instructors, "select one", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Start Date", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Editor("StartDate", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessage("StartDate", "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("End Date", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Editor("EndDate", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessage("EndDate", "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Show" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication10/WebApplication10/WebApplication10/Views/Instructors/Index.cshtml
@model IEnumerable<WebApplication10.Models.Instructor>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>



<p>@Html.ActionLink("Filter by Professor", "Filter")</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.ID })
            </td>
        </tr>
    }

</table>

WebApplication10/WebApplication10/WebApplication10/Views/Instructors/ListOfStudents.cshtml
@model IEnumerable<WebApplication10.Models.Enrollment>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Student.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Student.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grade)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Student.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Student.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>
        </tr>
    }
</table>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>